### ISSUE TITLE
[NES] Mapper data is wrong in database browser

### ISSUE THREAD

**Issue by sanni** [vpelletier/cartreader#3]
Left 10.4, right 10.4 trim

![IMG_1669](https://user-images.githubusercontent.com/19169494/197415352-2efb24d9-67fd-4345-999f-9fd26edecc44.JPG)
![IMG_1670](https://user-images.githubusercontent.com/19169494/197415353-2293693c-80c3-45a9-a48e-6911297418bb.JPG)
![IMG_1671](https://user-images.githubusercontent.com/19169494/197415355-fa53d491-4ae9-4302-8573-2d481e047c9b.JPG)

**Comment by vpelletier** [comment]
Should be fixed by 6551b80365a04f9ff242e7b86153ec6feb4591b4 .

(dummy edit because I posted before pushing, preventing github from generating the commit link)
